---
title: "Software Installation"
author: "Biology 6100 - Computational Biology"
date: "Spring 2026"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---
Here are the software packages you need to load onto your computer for this course. These programs work on Mac or Windows computers. They are free, safe, and do not take up much disk space. If you already have some of these programs installed, please check to make sure you are using the latest versions.

Before you begin downloading software, please make sure that your operating system (Windows, Linux, or iOS) and browser (Windows Explorer, Firefox, Chrome etc.) are as up-to-date as possible, and that you have installed all the most current patches and updates. The older and more out-of-date your software is, the harder it is to get everything working properly.

Go to each software page and follow the instructions for downloading the installer and running it. The installer will go through a number of steps. Always use the complete installation with the default choices at each step. 

Installing new software can sometimes be tricky. If you run into any issues please contact me or George, and we should be able to help you out.


## Github

GitHub is a free web-based repository for storing and updating your computer code, collaborating with others on documents and coding, and hosting your webpages. We will use GitHub extensively in this course. During the first week of class, you will start by building your own GitHub repository and website, and you will post all of your homeworks and exercises to this website during the semester. It will be an on-line "portfolio" of your work. Register for free GitHub account below, and be sure to record your user name and password for future use.

[register For GitHub](https://github.com/)

## R
R is the basic computational language we will use in this class. We will use R not only for coding, but also for taking notes, displaying code, and creating slides and graphs. The latest version of R (12 December 2025) is 4.5.2.   

[download R](http://lib.stat.cmu.edu/R/CRAN/)


## Python 3 (Miniconda)
Miniconda is a tool that helps install and organize Python and the software packages it uses. We will use Miniconda in this class to make sure everyone is working with the same setup, which reduces technical problems and makes it easier to follow along with examples and assignments.The Miniconda installer we will use is the latest version available at the start of the semester, which is the 12-2025 build.
  
[download Miniconda](https://repo.anaconda.com/miniconda/)

## Positron
Positron is an IDE (Integrated Development Environment), which is a special editor that makes it much easier to use R and Python and adds a number of useful features. **Make sure you have installed/updated R first before you install/update RStudio**. Choose either the Windows or Mac OS installer.



[download Positron](https://positron.posit.co/download.html)


## Installing LaTeX and other useful packages
If you already have R and Positron installed, you may want to try to add a few packages that we will be using.

LaTeX (pronounced "la-tech") is a typesetting language that renders plain text to a pdf, and is used by RStudio (and other programs). In the past, getting LaTeX installed properly was a major hair-pulling exercise during the first week of class, particularly for older Windows machines.

Fortunately, life got a lot easier a few years ago with the release of the `tinytex` R package by Yihui Xi. We only need to use this package once to install LaTeX. Two other R packages that we will use frequently are `tidyverse` and `patchwork`. All three packages are now available on CRAN.

If you already know how to install packages in R (either by issuing commands from the original R terminal or through the GUI in RStudio), go ahead and install `tinytex`, `tidyverse`, and `patchwork`. If you don't know how to install R packages, please contact me or George, and we will step you through it.

## Text editors
Plain text files are the common currency of all computational tools, and a plain text editor is also wonderful for composing text without any formatting distractions. Among its many uses, a good plain text editor allows you to search and replace using regular expressions, an incredibly powerful tool. Although there are simple editors that are installed by default on your Mac or Windows machines, they are not true plain text editors and should be avoided. There are many good plain text editors, some free, and some for sale, that you can find for your Mac or Windows machine. In fact, the RStudio itself can function as a simple text editor (although it is not so good for regular expressions, which is what we will be using it for). For this course, download and install one of the following: 


[download Notepad++ for Windows](https://notepad-plus-plus.org/)


[download BBedit for Mac](http://www.barebones.com/products/bbedit/index.html)

The "free" versions of this software will be fine for our use in this course.


